# 数据库设置
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        #主库
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://172.31.53.78:3306/qywx_intention_mayu?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: Iflytek1212
          driver-class-name: com.mysql.jdbc.Driver
#  data:
#    mongodb:
#      base:
#        uri: mongodb://qywx:iflytek123!@192.168.30.23:27117,192.168.30.22:27117,192.168.30.21:27117/qywx_prod
#        database: qywx_prod
#      intention:
#        uri: mongodb://qywx:iflytek123!@192.168.30.23:27117,192.168.30.22:27117,192.168.30.21:27117/qywx_intention
#        database: qywx_intention
  # mongodb配置
  data:
    mongodb:
      uri: mongodb://10.40.7.26:27017/play
      #uri: mongodb://qywx:iflytek123!@188.106.25.88:27017/qywx_basehistory
  #      uri: mongodb://10.40.7.26:27017/sas_multi_test_gzh_hbyd
  jackson:
    time-zone: GMT+8
  aop:                        # AOP
    auto: true                # Add @EnableAspectJAutoProxy.
    proxy-target-class: true  # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
  ################################Redis配置##################################
  redis:
    # Redis数据库索引（默认为0）
    database: 6
    # Redis服务器地址
    host: 10.40.7.76
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Fwts#2023
    # spring-data 可支持jedis，也可支持 lettuce两种客户端
    jedis:
      pool:
        max-active: 64
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池中的最小空闲连接
        min-idle: 8
    # 连接超时时间（毫秒)
    timeout: 2000
    sentinel:
      master: mymaster
      nodes: 10.40.7.76:26380
  # 集成MQ配置
  rabbitmq:
    host: 10.40.7.67
    port: 5672
    username: yuma5
    password: Mayu8119
    virtual-host: /
  # 邮箱配置
  # smtp 服务器地址
  mail:
    host: smtp.126.com
    #smtp 服务器的端口25/ssl 465
    port: 465
    #配置邮箱用户名
    username: qywxai_service@126.com
    #配置申请到的授权码
#    password: UVITONTRRMPPQEQT
    password: JHNOTZBNGTDPQLNN
    #配置邮件编码
    default-encoding: UTF-8
    #配置SSL加密工厂
    properties.mail.smtp.socketFactory.port: 465
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    properties.mail.smtp.auth: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.debug: true


#elasticsearch 配置
elasticsearch:
  ip:
    restHighLevelClient: 10.40.7.26
  port:
    restHighLevelClient: 9200
  index: indexvoice_test_faw_vw
  #  index: indexvoice_142
  hotWordIndex: hotword_test_faw_vw
  faw: faw_service_quality_test_faw_vw

# MQ配置
rabbit:
  queueName:
    # 判断服务类型客户需求是否已经解决
    delayJudgeKhServiceStatus: delayJudgeKhServiceStatusQueue
jk:
  qualityTask:
    semaphore: 3
# 对亚信消息推送的监控
message:
  monitor:
    # 推送动作中断监控定时任务开关
    switch: false
#    cron: 0 0/1 * * * ?
    cron: 0 0/01 * * * ?
    # 告警间隔(分钟)
    alarmIntervalMinutes: 30
    # 延迟判定时间(分钟)
    delayThresholdMinutes: 30
    # 多少次延迟后进行告警
    alarmIfDelayCount: 10
    # 中断判定时间(分钟)
    suspendThresholdMinutes: 10
    # 中断判定机制的生效范围(24小时制, 多个区间以逗号分割)
    suspendValidTimeRange: 07:30-22:00,
    email:
      subject: 【企业微信消息推送告警】
      sendTo: wanyysss@163.com, seaveany@163.com, 470751407@qq.com
      delayText: 企业微信数据同步异常，已连续10次推送动作延迟30分钟以上！延迟消息msgId样本：%s
      pushSuspendText: 企业微信数据同步异常，亚信侧已超过10分钟未进行数据推送..

# 星火大模型的接入，APPID：e86a3d40
bigModel:
  httpUrl: https://spark-api-open.xf-yun.com/v1/chat/completions
  printPromptLog: false
  configOne:
    apiKey: f7aa33c0339947ae6b8470e201acf2d5
    apiSecret: ZDg1NTc1OTBmMDYxZjNjMWNlODRjNTM5
    bigModeVersion: lite
  # 会话分类流程-重跑时使用50路的max版本 (appId:1aa962fb)
  configTwo:
    apiKey: f7aa33c0339947ae6b8470e201acf2d5
    apiSecret: ZDg1NTc1OTBmMDYxZjNjMWNlODRjNTM5
    bigModeVersion: lite
#    apiKey: 64115bc95bbd7f841ee81e93121480d5
#    apiSecret: NTliYTIyNWMxYWE2ZGJkZWY3NDM3ODc2
#    bigModeVersion: generalv3.5