# 数据库设置
spring:
  # mongodb配置
  data:
    mongodb:
#      uri: mongodb://10.40.7.26:27017/sas_multi_test_hunanyd_wh
      uri: mongodb://10.40.7.26:27017/play
  jackson:
    time-zone: GMT+8
  aop:                        # AOP
    auto: true                # Add @EnableAspectJAutoProxy.
    proxy-target-class: true  # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
  ################################Redis配置##################################
  redis:
    # Redis数据库索引（默认为0）
    database: 6
    # Redis服务器地址
    # host: 10.40.7.26
    host: 10.40.7.76
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Fwts#2023
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 64
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池中的最小空闲连接
        min-idle: 8
    # 连接超时时间（毫秒)
    timeout: 2000
    sentinel:
      master: mymaster
      nodes: 10.40.7.76:26380

  # 邮箱配置
  # smtp 服务器地址
  mail:
    host: smtp.126.com
    #smtp 服务器的端口25/ssl 465
    port: 465
    #配置邮箱用户名
    username: qywxai_service@126.com
    #配置申请到的授权码
#    password: UVITONTRRMPPQEQT
    password: JHNOTZBNGTDPQLNN
    #配置邮件编码
    default-encoding: UTF-8
    #配置SSL加密工厂
    properties.mail.smtp.socketFactory.port: 465
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    properties.mail.smtp.auth: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.debug: true


#elasticsearch 配置
elasticsearch:
  ip:
    restHighLevelClient: 10.40.7.26
  port:
    restHighLevelClient: 9200
  index: indexvoice_test_faw_vw
  #  index: indexvoice_142
  hotWordIndex: hotword_test_faw_vw
  faw: faw_service_quality_test_faw_vw

# 对亚信消息推送的监控
message:
  monitor:
    # 推送动作中断监控定时任务开关
    switch: false
#    cron: 0 0/1 * * * ?
    cron: 0 0/01 * * * ?
    # 告警间隔(分钟)
    alarmIntervalMinutes: 30
    # 延迟判定时间(分钟)
    delayThresholdMinutes: 30
    # 多少次延迟后进行告警
    alarmIfDelayCount: 10
    # 中断判定时间(分钟)
    suspendThresholdMinutes: 10
    # 中断判定机制的生效范围(24小时制, 多个区间以逗号分割)
    suspendValidTimeRange: 07:30-22:00,
    email:
      subject: 【企业微信消息推送告警】
      sendTo: wanyysss@163.com, seaveany@163.com, 470751407@qq.com
      delayText: 企业微信数据同步异常，已连续10次推送动作延迟30分钟以上！延迟消息msgId样本：%s
      pushSuspendText: 企业微信数据同步异常，亚信侧已超过10分钟未进行数据推送..